dns_provider:
    hetzner: 
        nameserver:
            - "1.1.1.1"
            - "8.8.8.8"
# Original hetzern fÃ¼hren zu einem Fehler
#            - "2a01:4f8:0:1::add:1010"
#            - "2a01:4f8:0:1::add:9999"
#            - "2a01:4f8:0:1::add:9898"
    other:
        nameserver:
            - "1.1.1.1"
            - "8.8.8.8"
