---
# Stand: 2019-06-18
#
# Super node 2

ansible_host: "{{inventory_hostname_short}}.freifunk-rhein-sieg.net"

provider: 'hetzner'

supernode:
    number: 2
    hostname: "{{inventory_hostname_short}}"
    fqdn: "ff"
    asn: 65201

ffrl:
    iface: "ffrl_uplink"
    IPv4: 
      addr: 185.66.193.127
    IPv6: 
      prefix48: 2a03:2260:301a
      addr: "2a03:2260:301a::{{ supernode.number }}"
      net: 2a03:2260:301a::/48

## GRE Tunnel definition

#Endpunkte

    # bb-a.ak.ber 185.66.195.0
    # bb-b.ak.ber 185.66.195.1
    # bb-a.ix.dus 185.66.193.0
    # bb-b.ix.dus 185.66.193.1
    # bb-a.fra3.fra 185.66.194.0
    # bb-b.fra3.fra 185.66.194.1
gre:
  ber_a:
    description: "Rheinland Backbone Berlin A"
    enabled: true
    remote: '185.66.195.0'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}ber_a'
    address: '100.64.10.55'
    daddress: '100.64.10.54'
    network: '100.64.10.54/31'
    inet6: 2a03:2260:0:524::2
    dinet6: 2a03:2260:0:524::1
    asn: 201701
  ber_b:
    description: "Rheinland Backbone Berlin B"
    enabled: true
    remote: '185.66.195.1'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}ber_b'
    address: '100.64.10.61'
    daddress: '100.64.10.60'
    network: '100.64.10.60/31'
    inet6: 2a03:2260:0:527::2
    dinet6: 2a03:2260:0:527::1
    asn: 201701
  dus_a:
    description: "Rheinland Backbone Duesseldorf A"
    enabled: true
    remote: '185.66.193.0'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}dus_a'
    address: '100.64.10.59'
    daddress: '100.64.10.58'
    network: '100.64.10.58/31'
    inet6: 2a03:2260:0:526::2
    dinet6: 2a03:2260:0:526::1
    asn: 201701
  dus_b:
    description: "Rheinland Backbone Duesseldorf B"
    enabled: true
    remote: '185.66.193.1'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}dus_b'
    address: '100.64.10.65'
    daddress: '100.64.10.64'
    network: '100.64.10.64/31'
    inet6: 2a03:2260:0:529::2
    dinet6: 2a03:2260:0:529::1
    asn: 201701
  fra_a:
    description: "Rheinland Backbone Frankfurt A"
    enabled: true
    remote: '185.66.194.0'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}fra_a'
    address: '100.64.10.57'
    daddress: '100.64.10.56'
    network: '100.64.10.42/31'
    inet6: 2a03:2260:0:525::2
    dinet6: 2a03:2260:0:525::1
    asn: 201701
  fra_b:
    description: "Rheinland Backbone Frankfurt B"
    enabled: true
    remote: '185.66.194.1'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}fra_b'
    address: '100.64.10.63'
    daddress: '100.64.10.62'
    network: '100.64.10.62/31'
    inet6: 2a03:2260:0:528::2
    dinet6: 2a03:2260:0:528::1
    asn: 201701

ul_mesh_MAC: a2:8c:ae:6f:f7:20
...
