---
# Super node 2
sn_number: 2
sn_hostname: voreifel2
sn_dhcp_range: 10.152.81.0 10.152.94.254
sn_mesh_IPv6: 2a03:2260:121:2000::1
sn_mesh_IPv6_net: 2a03:2260:121:2000::/64
sn_mesh_IPv6_xfer: 2a03:2260:121:2000::2
sn_mesh_IPv4: 10.152.80.1
sn_mesh_IPv4_brcast: 10.152.95.255
sn_mesh_IPv4_net: 10.152.80.0
sn_mesh_IPv4_netmask: 255.255.240.0

sn_mesh_IPv4_xfer: 10.152.80.2
sn_mesh_MAC: a2:8c:ae:6f:f7:02
ul_mesh_MAC: a2:8c:ae:6f:f7:20

sn_ffrl_IPv4: 185.66.193.127

## Lokaler exit
#sn_local_exit: 1

## Exit über FFRL
sn_exit: 1

# brauchen wir aktuell für die tunneldigger konfiguration
# sollte durch ansible variable ausgetauscht werden
sn_interface_name: ens18
yanic_domain: voreifel2
...
